### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by Antonio-Laguna** [robweber/xbmclibraryautoupdate#39]
I've just installed it, added the paths and I get this on the logs:

```
09:40:13.735 T:1463808768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Exactly 5 or 6 columns has to be specified for iteratorexpression.
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/service.libraryautoupdate/default.py", line 6, in <module>
                                                AutoUpdater().runProgram()
                                              File "/home/osmc/.kodi/addons/service.libraryautoupdate/service.py", line 38, in __init__
                                                self.createSchedules(True)
                                              File "/home/osmc/.kodi/addons/service.libraryautoupdate/service.py", line 190, in createSchedules
                                                aJob.next_run = self.calcNextRun(aJob.expression, self.last_run)
                                              File "/home/osmc/.kodi/addons/service.libraryautoupdate/service.py", line 216, in calcNextRun
                                                cron = croniter(cronExp,startTime)
                                              File "/home/osmc/.kodi/addons/service.libraryautoupdate/resources/lib/croniter.py", line 60, in __init__
                                                raise ValueError(self.bad_length)
                                            ValueError: Exactly 5 or 6 columns has to be specified for iteratorexpression.
                                            -->End of Python script error report<--```

**Comment by robweber** [comment]
Did you also set a custom cron expression? The error has to do with parsing the cron expression for the timer. If you didn't please let me know what increment you selected so I can take a look.

**Comment by Antonio-Laguna** [comment]
I didn't,  It has the default ones: `0 */2 * * *`

**Comment by Antonio-Laguna** [comment]
I've fixed it. It seems you can't cancel when adding a source so I had a couple of empty items on the sources path. Deleted them and it went smooth
