### ISSUE TITLE
Crash on Manual Run

### ISSUE THREAD

**Issue by benyjr** [robweber/xbmclibraryautoupdate#60]
I installed this addon on Kodi 19 Matrix running on Ubuntu 20.04 from the Kodi repo.
I set it up with a simple 6 hour timer.  When I run the addon manually, i get a popup message saying "Library Auto Update error. Check the log for more info."

The Kodi logs report the following errors:

2021-04-30 22:49:28.750 T:2377187    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-04-30 22:49:28.753 T:2433259    INFO <general>: initializing python engine.
2021-04-30 22:49:29.385 T:2433259   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: '6'
                                                   Traceback (most recent call last):
                                                     File "/home/benyjr/.kodi/addons/service.libraryautoupdate/manual.py", line 5, in <module>
                                                       autoUpdate = AutoUpdater()
                                                     File "/home/benyjr/.kodi/addons/service.libraryautoupdate/resources/lib/service.py", line 36, in __init__
                                                       self.createSchedules(True)
                                                     File "/home/benyjr/.kodi/addons/service.libraryautoupdate/resources/lib/service.py", line 172, in createSchedules
                                                       aSchedule.expression = self.checkTimer('video')
                                                     File "/home/benyjr/.kodi/addons/service.libraryautoupdate/resources/lib/service.py", line 217, in checkTimer
                                                       result = '0 */' + str(self.timer_amounts[utils.getSetting(settingName + "_timer")]) + ' * * *'
                                                   KeyError: '6'
                                                   -->End of Python script error report<--

**Comment by robweber** [comment]
Good catch. Looks like the new settings format returns the value selected, not the index of that value like the old one did. Any hourly values after 4hrs threw an error. Should be fixed now, will push to repo after some checks.
